/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CausesIndexRouteImport } from './routes/causes.index'
import { Route as CausesIdRouteImport } from './routes/causes.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin/site-settings'
import { Route as AdminSetup2faRouteImport } from './routes/admin/setup-2fa'
import { Route as AdminPaymentSettingsRouteImport } from './routes/admin/payment-settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCausesRouteImport } from './routes/admin/causes'

const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesIndexRoute = CausesIndexRouteImport.update({
  id: '/causes/',
  path: '/causes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesIdRoute = CausesIdRouteImport.update({
  id: '/causes/$id',
  path: '/causes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/admin/site-settings',
  path: '/admin/site-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetup2faRoute = AdminSetup2faRouteImport.update({
  id: '/admin/setup-2fa',
  path: '/admin/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentSettingsRoute = AdminPaymentSettingsRouteImport.update({
  id: '/admin/payment-settings',
  path: '/admin/payment-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCausesRoute = AdminCausesRouteImport.update({
  id: '/admin/causes',
  path: '/admin/causes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/admin/causes': typeof AdminCausesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/setup-2fa': typeof AdminSetup2faRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/causes/$id': typeof CausesIdRoute
  '/causes/': typeof CausesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/admin/causes': typeof AdminCausesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/setup-2fa': typeof AdminSetup2faRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/causes/$id': typeof CausesIdRoute
  '/causes': typeof CausesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/admin/causes': typeof AdminCausesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/setup-2fa': typeof AdminSetup2faRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/causes/$id': typeof CausesIdRoute
  '/causes/': typeof CausesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/admin/causes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/setup-2fa'
    | '/admin/site-settings'
    | '/admin/users'
    | '/causes/$id'
    | '/causes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/admin/causes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/setup-2fa'
    | '/admin/site-settings'
    | '/admin/users'
    | '/causes/$id'
    | '/causes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/admin/causes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/setup-2fa'
    | '/admin/site-settings'
    | '/admin/users'
    | '/causes/$id'
    | '/causes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  AdminCausesRoute: typeof AdminCausesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentSettingsRoute: typeof AdminPaymentSettingsRoute
  AdminSetup2faRoute: typeof AdminSetup2faRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CausesIdRoute: typeof CausesIdRoute
  CausesIndexRoute: typeof CausesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes/': {
      id: '/causes/'
      path: '/causes'
      fullPath: '/causes/'
      preLoaderRoute: typeof CausesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes/$id': {
      id: '/causes/$id'
      path: '/causes/$id'
      fullPath: '/causes/$id'
      preLoaderRoute: typeof CausesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/admin/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup-2fa': {
      id: '/admin/setup-2fa'
      path: '/admin/setup-2fa'
      fullPath: '/admin/setup-2fa'
      preLoaderRoute: typeof AdminSetup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-settings': {
      id: '/admin/payment-settings'
      path: '/admin/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AdminPaymentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/causes': {
      id: '/admin/causes'
      path: '/admin/causes'
      fullPath: '/admin/causes'
      preLoaderRoute: typeof AdminCausesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  AdminCausesRoute: AdminCausesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentSettingsRoute: AdminPaymentSettingsRoute,
  AdminSetup2faRoute: AdminSetup2faRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CausesIdRoute: CausesIdRoute,
  CausesIndexRoute: CausesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
